name: LANCommander Release

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: frabert/replace-string-action@v2
      name: Trim Tag Ref
      id: trim_tag_ref
      with:
        string: '${{ github.ref }}'
        pattern: 'refs/tags/v'
        replace-with: ''

    - uses: frabert/replace-string-action@v2
      name: Swap Path Backslashes
      id: swap_path_backslashes
      with:
        string: '${{ github.workspace }}'
        pattern: '\\'
        replace-with: '/'
        flags: g

    - uses: frabert/replace-string-action@v2
      name: Snake Case Version
      id: snake_case_version
      with:
        string: '${{ steps.trim_tag_ref.outputs.replaced }}'
        pattern: '.'
        replace-with: '_'
        flags: g

    # dotnet
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    # Playnite
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
    - name: Restore NuGet packages
      run: nuget restore LANCommander.sln

    - name: Build and Publish PowerShell Module
      run: msbuild LANCommander.PowerShell/LANCommander.PowerShell.csproj /p:Configuration=Release /p:OutputPath=Build /p:Version="${{ steps.trim_tag_ref.outputs.replaced }}" /p:InformationalVersion="${{ steps.trim_tag_ref.outputs.replaced }}"

    - name: Build and Publish Library
      run: msbuild LANCommander.Playnite.Extension/LANCommander.PlaynitePlugin.csproj /p:Configuration=Release /p:OutputPath=Build /p:Version="${{ steps.trim_tag_ref.outputs.replaced }}" /p:InformationalVersion="${{ steps.trim_tag_ref.outputs.replaced }}"
    - name: Download Playnite Release
      uses: robinraju/release-downloader@v1.7
      with:
        repository: JosefNemec/Playnite
        tag: 10.32
        fileName: Playnite1032.zip
    - name: Extract Playnite
      run: Expand-Archive -Path Playnite1032.zip -DestinationPath Playnite
    - name: Update Manifest Versioning
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: "LANCommander.Playnite.Extension/Build/extension.yaml"
        propertyPath: "Version"
        value: "${{ steps.trim_tag_ref.outputs.replaced }}"
        commitChange: false
    - name: Copy PowerShell Module to Playnite Extension
      run: Copy-Item LANCommander.PowerShell/Build/LANCommander.PowerShell.* -Destination LANCommander.Playnite.Extension/Build
    - name: Run Playnite Toolbox
      run: Playnite/Toolbox.exe pack LANCommander.Playnite.Extension/Build .
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: LANCommander.PlaynitePlugin_48e1bac7-e0a0-45d7-ba83-36f5e9e959fc_${{ steps.snake_case_version.outputs.replaced }}.pext
        name: LANCommander.PlaynitePlugin_48e1bac7-e0a0-45d7-ba83-36f5e9e959fc_${{ steps.trim_tag_ref.outputs.replaced }}.pext